services:
  postgres:
    image: postgres:16-alpine
    container_name: um_api_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-um_api_postgres}"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - um_api_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: um_api_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-ristep@gmail.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-Leprakon!2025}"
      PGADMIN_CONFIG_SERVER_MODE: "True"
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - um_api_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  um_api_network:
    driver: bridge
